apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: roboshop 
  labels: 
    appName: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
       appName: {{ .Values.name }}
  template:
    metadata:
      labels:
        appName: {{ .Values.name }}
    spec:
        containers:  
            - name: {{ .Values.name }}
              image: docker.io/manupanand/{{ .Values.name }}:latest 
              ports: 
                - containerPort: {{ .Values.cport }}
              envFrom:
                 - secretRef:  
                     name: {{ .Values.name }}
              resources: 
                 {{- toYaml .Values.resources | nindent 6 }}
---

 
