# use condition because only need for cataloguge and shipping
{{- if .Values.schema.enabled -}} # if values enabed-schema is true then dp # main file enabe it false always-values.yaml
apiVersion: batch/v1
kind: Job 
metadata: 
  name: {{ .Values.name }}-schema
  namespace: roboshop 
  labels: 
    appName: {{ .Values.name }}-schema
spec:  
  template: 
    spec:  
      containers: # loop/rnage over each contianers
        {{- range .Values.schema.containers }}
        - name: {{ $.Values.name }}-{{ . }}
        image: docker.io/manupanand/{{ . }}:latest # {{ . }} name per container
        env: 
          {{- toYaml  $.Values.schema.env | nindent 12 }} # to acces the values in loop use $
        {{- end }}
      restartPolicy: Never 
  backoffLimit: 0
{{- end -}}
# suppose if we have three seperate containers for one-application -shipping need seperate container
#either edit run script to do it one in one container or 
# use loop/range-for each in helm chart